- name: Install Python Package
  apt:
    name: python3
    update_cache: yes
    state: present

- name : Install Let's Encrypt Package
  apt:
    name: "{{ certbot_package }}"
    update_cache: yes
    state: present

- name: Create and Install Cert Using {{ certbot_plugin }} Plugin
  command: "certbot --{{ certbot_plugin }} -d  {{ certbot_site_name }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect"
  args:
    creates: /path/to/file

- name: Set Letsencrypt Cronjob for Certificate Auto Renewal
  cron:
    name: letsencrypt_renewal
    special_time: monthly
    job: "/usr/bin/certbot renew"
    state: present
